const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#FF6B35",
    background: "#FFFBF8",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F4EC",
    secondaryForeground: "#2D4739",
    muted: "#F5F0EB",
    mutedForeground: "#8A8A8E",
    accent: "#2D4739",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E8E0D8",
    input: "#E8E0D8",
  },
  dark: {
    text: "#FFFBF8",
    tint: "#FF8A65",
    background: "#0F0F0F",
    foreground: "#FFFBF8",
    card: "#1C1C1E",
    cardForeground: "#FFFBF8",
    primary: "#FF8A65",
    primaryForeground: "#1C1C1E",
    secondary: "#1E2D26",
    secondaryForeground: "#A8D5B5",
    muted: "#2C2C2E",
    mutedForeground: "#8A8A8E",
    accent: "#4CAF70",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#3A3A3C",
    input: "#3A3A3C",
  },
  radius: 16,
};

export default colors;
