const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#7C3AED",
    background: "#FAF5FF",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#4C1D95",
    muted: "#F3EEFF",
    mutedForeground: "#8B7BA8",
    accent: "#5B21B6",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E5D8FA",
    input: "#E5D8FA",
  },
  dark: {
    text: "#F5F0FF",
    tint: "#A78BFA",
    background: "#0F0A1E",
    foreground: "#F5F0FF",
    card: "#1A1030",
    cardForeground: "#F5F0FF",
    primary: "#A78BFA",
    primaryForeground: "#1A1030",
    secondary: "#2E1F5E",
    secondaryForeground: "#C4B5FD",
    muted: "#231848",
    mutedForeground: "#8B7BA8",
    accent: "#7C3AED",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#3D2D6E",
    input: "#3D2D6E",
  },
  radius: 16,
};

export default colors;
